name: patente_b_flutter
description: "Patente B Quiz App - Preparazione esame patente di guida"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.1
  flutter_tts: ^4.0.2
  shared_preferences: ^2.2.2
  collection: ^1.18.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1
  http: ^1.6.0
  translator: ^1.0.0
  audioplayers: ^6.5.1
  path_provider: ^2.1.5
  video_player: ^2.10.1
  chewie: ^1.13.0
  youtube_player_iframe: ^5.1.2
  # New packages for monetization features
  share_plus: ^7.2.2
  url_launcher: ^6.2.3
  qr_flutter: ^4.1.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
    - assets/images/quiz/
    - assets/images/segnali/
    - assets/images/theory-icons/
    - assets/images/theory-pdf/
    - assets/images/theory/lesson1/
    - assets/images/theory/lesson4/
    - assets/images/theory/lesson5/
    - assets/images/theory/lesson7/
    - assets/data/italian-tests/
