name: patente_b_flutter
description: "Quiz Patente B C CE - App completa per preparazione esame patente di guida italiana con quiz ministeriali, teoria e simulazioni"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.1
  flutter_tts: ^4.0.2
  shared_preferences: ^2.2.2
  collection: ^1.18.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1
  http: ^1.6.0
  translator: ^1.0.0
  audioplayers: ^6.5.1
  path_provider: ^2.1.5
  video_player: ^2.10.1
  chewie: ^1.13.0
  youtube_player_iframe: ^5.1.2
  # New packages for monetization features
  share_plus: ^7.2.2
  url_launcher: ^6.2.3
  qr_flutter: ^4.1.0
  uuid: ^4.3.3
  crypto: ^3.0.3
  device_info_plus: ^9.1.1
  package_info_plus: ^8.1.0
  pinput: ^3.0.1
  image_picker: ^1.2.1
  firebase_storage: ^12.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
    - assets/images/
    - assets/images/quiz/
    - assets/images/segnali/
    - assets/images/theory-icons/
    - assets/images/theory-pdf/
    - assets/images/theory/lesson1/
    - assets/images/theory/lesson4/
    - assets/images/theory/lesson5/
    - assets/images/theory/lesson7/
    - assets/images/theory/thumbnails/
    - assets/images/dashboard/
    - assets/images/licenses/
    - assets/data/italian-tests/

# Splash Screen Configuration
flutter_native_splash:
  color: "#0047AB"
  color_dark: "#001F3F"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  web: false
  android_12:
    color: "#0047AB"
    image: assets/images/splash_logo.png

